fs = require('fs');

var textList = [
    "2030: The Year We Make Contact",
    "3D Glasses",
    "8 Eyes",
    "A (very) non-addictive game",
    "A day in the life of",
    "Aardvarks",
    "Abandoned",
    "Absolute",
    "Abstract",
    "Achievements",
    "Achilles Heel",
    "Adaptation",
    "Add a rule, remove a rule",
    "Adjectives",
    "Advanced mathematics",
    "Advancing Wall of Doom",
    "Adventure game",
    "Afterlife",
    "Age",
    "Aggression",
    "AI Opponent",
    "Air",
    "Alcohol",
    "Alexander the Great",
    "Algorithms",
    "Alien skies",
    "Aliens",
    "All Humans are dead",
    "All Natural",
    "All Your Base",
    "Alpha Men",
    "Alphabet",
    "Alternatives",
    "Ambiguity",
    "Ambiguous Controls",
    "And what now?",
    "Android Hell",
    "Angular Momentum",
    "Animal Kingdom",
    "Animals",
    "Annihilation",
    "Antarctica",
    "Anthropomorphism",
    "Anti-collectibles / Anti-collect-a-thon",
    "Anti-gravity",
    "Antonyms",
    "Any Fiction 100 years + old",
    "Apocalypse",
    "Apologise",
    "April the Twentieth",
    "Aquarium",
    "Arcade Games",
    "Architecture",
    "Armada",
    "Armageddon",
    "Arms Race",
    "Artificial Intelligence",
    "Ascension",
    "Asian carp",
    "Astrobiology",
    "Asymmetrical Multiplayer",
    "Atmosphere",
    "Attack of the Giant Monster!",
    "Attack of the Zombie Gnomes from Hell",
    "Attraction",
    "Augmented Reality",
    "Authentic",
    "Autobiography",
    "Avalanche",
    "Bacon",
    "Bacteria",
    "Bad is Good",
    "Bad luck",
    "Baked Goods as Characters",
    "Baked Goods as Weapons",
    "Balance",
    "Balloon!",
    "Bank Job",
    "Bards",
    "Batman",
    "Bats",
    "Batteries not included",
    "Battle of Archenemies",
    "Beards, Moustaches and crazy facial hair",
    "Before and After",
    "Betrayal",
    "Betrayal as a gameplay mechanic",
    "Bicycle",
    "Biological Threat",
    "Birds",
    "Black Holes",
    "Bleeding & Leaking",
    "Bleeding / Leaking",
    "Blindness",
    "Blood/Bloodyness",
    "Board Game",
    "Board Games",
    "Body Building",
    "Body parts",
    "Boredom",
    "Boring and Generic Theme that Does Little to Stimulate Creativity",
    "Bosses",
    "Bouncy",
    "Boundless",
    "Braiding",
    "Breaking laws (of physics especially)",
    "Breaking the rules",
    "Bridge",
    "British Simulator",
    "Buggy game, to win you have to workaround the bugs. or die trying.",
    "Bugs",
    "Bullet Hell",
    "Bullet Time",
    "Bureaucracy",
    "Buried",
    "Burning",
    "Burrowing",
    "By our powers combined",
    "Byronic Hero",
    "Cables/Wires",
    "Cactus",
    "Cannibalism",
    "Cards",
    "Cash",
    "Castle",
    "Cat and Mouse",
    "Cats",
    "Cave",
    "Caverns",
    "Cellular automata",
    "Censorship",
    "Centrifugal Force",
    "Chain reaction",
    "Chainsaws",
    "Chance & Fate",
    "Chemical reaction",
    "Chickens",
    "Childhood",
    "Choose your own theme",
    "Circuits",
    "Classic Demo Effects (think Future Crew)",
    "Classic game, inverted roles",
    "Claustrophobia or Agorophobia",
    "Clay",
    "Claymation",
    "Climate Change",
    "Climb",
    "Clockwork",
    "Clouds",
    "Clowns",
    "Code Breaking",
    "Coffee",
    "Cogs",
    "Coincidence",
    "Cold",
    "Cold / Frozen",
    "Collecting",
    "Collective",
    "Collective Action",
    "Colonization",
    "Color",
    "Colossal",
    "Combined Arms",
    "Comedy As A Weapon",
    "Comic book",
    "Comic Mischief",
    "Commodore 64",
    "Companion",
    "Competition",
    "Conciousness",
    "Conduction or Conducting",
    "Confusion",
    "Connections",
    "Consequences",
    "Conservation of energy",
    "Conservation of Mass / Energy (i.e., after startup, game entities neither created nor destroyed)",
    "Conspiracy",
    "Constellations",
    "Construction",
    "Continuous motion",
    "Contraception",
    "Contrast",
    "Control",
    "Controversy-baiting",
    "Conundrum",
    "Conversation",
    "Cooking",
    "Cooperation",
    "Corporate Evil",
    "Corpse Stacking",
    "Crab people",
    "Crane Game",
    "Create a game that the computer plays, try to outsmart it",
    "Create or alter the laws of Physics",
    "Creepy Crawly",
    "Crew",
    "Crisis",
    "Cruel World",
    "Crustaceans vs Cetaceans",
    "Cryogenics/Cryonics",
    "Cryptozoology",
    "Cthulhu",
    "Cubes",
    "Curiosity",
    "Curses",
    "Cute",
    "Cute War",
    "Cyber warfare",
    "Cyberpunk",
    "Cyberspace",
    "Dancing Trees",
    "Dark Ages",
    "Darkness",
    "Data Collection and Analysis",
    "Database",
    "Death",
    "Decay",
    "Deception",
    "Deep holes",
    "Defense",
    "Deities",
    "Delayed reaction",
    "Delegation",
    "Delusions of Grandeur",
    "Democracy",
    "Demoscene",
    "Dentist",
    "Depression",
    "Detective",
    "Detectives",
    "Determinism",
    "Deviousness",
    "Diabetes",
    "Dictator",
    "Dimensional shift",
    "Diplomacy",
    "Direction",
    "Dirigibles, hot air balloons, airships, etc",
    "Discipline",
    "Disjoint",
    "Disorientation",
    "Dissolving",
    "Distorted perception",
    "Distress",
    "Distribution of knowledge",
    "Dive",
    "Divine Command Theory",
    "Don\\'t think, do.",
    "Doors",
    "Downfall",
    "Draw & Paint",
    "Dreaming",
    "Dreams",
    "Drinking",
    "Drums and drumming.",
    "Ducks",
    "Duel",
    "Duplicates",
    "Dwarves",
    "Dynamic Changing Characters",
    "Dystopia",
    "Earthquake",
    "Eat it Before it Eats You!",
    "Eating",
    "Economy",
    "Ecosystem",
    "Edge",
    "Educational",
    "Egg",
    "Elastic",
    "Elderly people",
    "Electricity",
    "Elephants",
    "Emoticons",
    "Empathic",
    "End of the World",
    "Endless War",
    "Enemies as Weapons",
    "Enemies of the Mind",
    "Enemy Is Cheating!",
    "English as a second language",
    "Epic",
    "Epidemic",
    "Ergonomics",
    "Eroticism",
    "Escape",
    "Everyone is a Friend",
    "Everything\\'s breakable",
    "Evil",
    "Evil Gnomes",
    "Evil Overlords",
    "Evil, defeat the lone hero!",
    "Evolution",
    "Excessive Explosions",
    "Existentialism",
    "Exit signs",
    "Exploration",
    "Explosions",
    "Extremes",
    "Fail to win",
    "Fairy Tale",
    "Falling",
    "Family",
    "Famous Boss Fights, Reimagined",
    "Fans",
    "Farming",
    "Fast and Slow (use both concepts)",
    "Fear of Clowns",
    "Ferrets",
    "Festivus",
    "Fight for your future",
    "Fighting",
    "Film Noir",
    "Financial Troubles",
    "Fire",
    "Fishing",
    "Flags",
    "Flashlight",
    "Flat",
    "Flight",
    "Flirting",
    "Floating",
    "Floating islands",
    "Flocking",
    "Flood",
    "Flora and Fauna",
    "Flow",
    "Flower Power",
    "Flowers",
    "Fluff",
    "Fluid",
    "Fluoride",
    "Flying",
    "Flying Dragons",
    "Flying Pigs",
    "Fog of War",
    "Food",
    "Food Chain",
    "For Ages 5 and Up",
    "Forest",
    "Four Seasons.",
    "Four seconds to midnight",
    "Fractal",
    "Freefall",
    "Friends",
    "Friends Forever! Never apart!",
    "Frozen",
    "Fruity",
    "Frustration",
    "Futility",
    "Game of life",
    "Game Programming",
    "Game within a game",
    "Gameworld is a sphere",
    "Gas",
    "Gears",
    "Gel Substances",
    "Gelatin",
    "Gender Equality",
    "Genetic",
    "Genius",
    "Gentlemen",
    "Gentlemen, you can\\'t fight in here, this is the war room!",
    "Geography",
    "Geometry",
    "Ghosts",
    "Giant Naked Men",
    "Gibs",
    "Gifts",
    "Gimmicky Mechanic",
    "Gladiators",
    "Gliding",
    "Glitch",
    "Global warming",
    "Globe",
    "Glow in the dark",
    "God(s) (or religion)",
    "Goliath",
    "Goo",
    "Good and Evil",
    "Goodbye",
    "Gore",
    "Gotchas",
    "Government Conspiracy",
    "Grapple",
    "Grappling (hooks or wrestling)",
    "Graveyards",
    "Gravity",
    "Greed",
    "Greek Mythology",
    "Grid Based",
    "Grill the baby",
    "Groundbreaking",
    "Gulliver\\'s Travels",
    "Guns. Lots of guns.",
    "H.P. Lovecraft",
    "Hacking",
    "Hello World",
    "Help the helpless",
    "Hercules",
    "Herding",
    "Hermits",
    "Heroes & Villains",
    "HG Wells Story",
    "Hiccups",
    "Hide and Seek",
    "Hide\\'n\\'seek",
    "High",
    "High-brow",
    "Highnoon",
    "Hiking",
    "Hints",
    "History",
    "History Rewritten",
    "Hitch hiker",
    "Hitchcock",
    "Hold the Line",
    "Holes",
    "Hollywood Physics",
    "Homages",
    "Horror",
    "Horses",
    "How everyone votes for the only theme you don\\'t have an idea for",
    "Hugging",
    "Humor",
    "Hunt",
    "Hydraulics / Hydrodynamics",
    "Hype",
    "Hyperspace",
    "I accidentally the whole thing",
    "I don\\'t understand how you can believe that!",
    "Ice/Igloos",
    "Ignorance is Bliss",
    "Illuminati",
    "Illusions",
    "I\\'m lost!!!\\'",
    "Imitation",
    "Immersion",
    "Immortality",
    "Impostors",
    "In Kazakhstan",
    "In the Zone",
    "Ineffective",
    "Inertia",
    "Inferno",
    "Infinity",
    "Influence",
    "Insanity",
    "Instant Death",
    "Insults",
    "Intelligent Design",
    "Intensity",
    "Intentionally broken",
    "Inter-continental Ballistic Missile",
    "Interesting Gameplay Mechanics",
    "Interface Screw",
    "Interference",
    "Intrigue",
    "Intuition",
    "Invasive advertisements",
    "Invention",
    "Inventory",
    "Inversion",
    "Invisibility",
    "Invulnerability isn\\'t all it\\'s cracked up to be",
    "Ironing",
    "Irony",
    "Irreplaceable",
    "Islands",
    "Isolation",
    "Items",
    "Jailbreak",
    "Japan",
    "Jargon",
    "Jealous boy/girlfriend",
    "Jello",
    "Jesters",
    "Jesus",
    "Jinx",
    "Journey",
    "Juice",
    "Jules Verne Story",
    "Jump",
    "Kangaroos",
    "Key Lime Pie",
    "Keys",
    "King",
    "Kittens",
    "Knitting",
    "Knocking Down",
    "Know when to quit",
    "Knowledge",
    "Labyrinth",
    "Lame meme",
    "Landing on things",
    "Large Hadron Collider (emphasis on the large)",
    "Laser Cats",
    "Lasers and Mirrors",
    "Late partygoers",
    "Layers",
    "Leadership",
    "Legs",
    "Lemonade stand",
    "Leprechauns",
    "Letting go",
    "Liars",
    "Library",
    "Lice",
    "Licorice",
    "Life in the atom",
    "Light & Shadow",
    "Lightning",
    "Limbs like these are hard to use",
    "Lines",
    "Linguistics/Translation/Interpretation",
    "Look After You",
    "Look behind you!",
    "Lose to win",
    "Losing to win",
    "Loss",
    "Lots of different endings",
    "Love",
    "Lowered expectations",
    "Luck",
    "Lurking",
    "Machinery and its Merits",
    "Macro Management",
    "Magnetic",
    "Magnetism",
    "Mankind",
    "Manly",
    "Many Missiles",
    "Mashup",
    "Masks",
    "Massively Single-player Online",
    "Mayans",
    "Maze/Labryinth",
    "Meat vs. Vegetables",
    "Mechanics and Gears",
    "Mechatronics",
    "Medical error",
    "Melancholy",
    "Menial labor",
    "Metagame",
    "Microscopic World",
    "Miracles",
    "Mirror",
    "Mirrors",
    "Misanthropy",
    "Misdirection",
    "Missing senses",
    "Modding",
    "Mold",
    "Monocles",
    "Mons",
    "Morocco",
    "Mountain Goats",
    "Mouse controls only",
    "Moustaches",
    "Muhammad",
    "Multiplayer",
    "Multiple types of health meters",
    "Murder!",
    "Mushrooms.",
    "Music",
    "Mustache",
    "Mutation",
    "My first time",
    "Mysteries",
    "Mythology",
    "Nachos",
    "Naked men",
    "Narcissism",
    "Narrative (tell a story)",
    "Negative Space",
    "Network",
    "Never the same game twice",
    "Nightmare",
    "Nihilism",
    "Nintendo Hard",
    "No Gravity, no Friction",
    "Noir",
    "Noise",
    "Non euclidean space",
    "Non Sequitur",
    "Non-Newtonian Physics",
    "Non-violent conflict",
    "Not Penny\\'s Boat",
    "Now!",
    "Nude beach management",
    "Odyssey",
    "Offspring",
    "One button",
    "One control, two games",
    "One hit and you die",
    "One Hit Point Wonder",
    "One way out",
    "Online high scores",
    "Oodles of noodles",
    "Opening cans/bottles",
    "Opposites",
    "Orange (the color, not the fruit)",
    "Orbit",
    "Order of operations",
    "Organisation",
    "Origin",
    "Other Worldly/Out of this world",
    "Outnumbered",
    "Outside My Comfort Zone",
    "Over-complication",
    "Overlords",
    "Over-simplification",
    "Owl!",
    "Ownership",
    "Oysters",
    "Pacifist",
    "Paints and Brushes",
    "Pandas",
    "Pandemic",
    "Paper",
    "Paper or Plastic",
    "Parallel",
    "Parallel Universes, multiverse",
    "Paranormal",
    "Particles",
    "Party Game",
    "Pasta",
    "Pastries",
    "Peak Oil",
    "Perpetual motion",
    "Pest Control",
    "Photography",
    "Physical Education (sports)",
    "Physics",
    "Pirates",
    "Planets",
    "Platformer",
    "Player-Driven Game logic",
    "Player-Driven Story",
    "Player-Driven Vehicle",
    "Player-generated story",
    "Player\\'s actions coming back to bite him/her in the keister",
    "Playing Real-Life",
    "Please enter your name",
    "Poetry",
    "Political",
    "Pollution",
    "Pop",
    "Portals",
    "Power",
    "Power Outage",
    "Power Plants",
    "Prehistoric madness",
    "Preparation",
    "Pretentious Art Game",
    "Prison",
    "Procedural Generation",
    "Programmer Art",
    "Programming",
    "Projectiles, bullets",
    "Propaganda",
    "Psychedelic",
    "Psychic Powers",
    "Psychology",
    "Psychonauts",
    "Pterodactyls",
    "Punk",
    "Puns",
    "Purposed Play (playing the game aides productivity)",
    "Pursuit",
    "Pyrotechnics",
    "Pyrrhic Victory",
    "Quality Control",
    "Quanta",
    "Quantum mechanics",
    "Quantum physics",
    "Quest",
    "Queues",
    "Quid Pro Quo",
    "Quiet",
    "Quilting",
    "Rabbits",
    "Race",
    "Radiation",
    "Rain",
    "Random controls/physics",
    "Randomness (never the same twice)",
    "Rappelling",
    "Reality TV",
    "Recurring dream",
    "Recursion",
    "Recycling",
    "Red Herring",
    "Redo a physical game + cool stuff",
    "Reflection",
    "Regression",
    "Relationships",
    "Relative",
    "Religion",
    "Remakes",
    "Renaissance",
    "Repair what\\'s broken",
    "Reptiles",
    "Research",
    "Resources (limited?)",
    "Respawn",
    "Return to Tesla City",
    "Revenge",
    "Reverse",
    "Reverse Engineering",
    "Reverse time",
    "Reverse/Replay",
    "Revolt",
    "Revolve!",
    "Rewind",
    "Rice",
    "Ridiculously Cute",
    "Risk vs Reward",
    "Roadkill",
    "Roads",
    "Roadtrip",
    "Robot",
    "Rock Climbing",
    "Rock Star Lifestyle",
    "Rock, Paper, Scissors",
    "Rogue Nanobots",
    "Roguelike",
    "Role Reversal",
    "Rollercoasters",
    "Roman Empire",
    "Roman Mythology",
    "Roman numerals",
    "Romance",
    "Ropes",
    "Rotation",
    "Roundabout methods",
    "Rube Goldberg like",
    "Rust",
    "Rythm",
    "Sacrifice",
    "Safari",
    "Sand",
    "Sandbox",
    "Scheme",
    "Schizophrenia",
    "Science",
    "Science Fiction",
    "Sci-fi",
    "Second and Third Themes Combined",
    "Secretary",
    "Secrets",
    "Select Start",
    "Seriously, WTF",
    "Sex",
    "Shadows",
    "Shakespeare",
    "Shapeshifting",
    "Shatter",
    "Sheep + Wolves",
    "Shoes",
    "Short Complete Story",
    "Showdown",
    "Shrinking resources",
    "Sickeningly Cute",
    "Sidekick",
    "Sidekicks Revenge",
    "Simplexity (complexity emerging from a simple design)",
    "Simulacrum",
    "Simulation and Persistence",
    "Simulator",
    "Simultaneous",
    "Single Enemy",
    "Singularity",
    "Size",
    "Slavery",
    "Sleepwalking",
    "Slippery Slope",
    "Slipstream",
    "Slow Motion",
    "Slow/fast",
    "Small Violent Robots",
    "Smell",
    "Smile",
    "Snails",
    "Snakes on a plane",
    "Sneaking",
    "Sniping",
    "Snow",
    "Social",
    "Social interaction",
    "Solar power",
    "Sound",
    "Sound is your friend",
    "Source of reality",
    "Space",
    "Space Opera",
    "Spacemarine",
    "Spaceship Earth",
    "Spaceships",
    "Spicy",
    "Spicy Food",
    "Spiders",
    "Spin",
    "Spinning",
    "Spoof",
    "Sports",
    "Sports Management",
    "Sports which could never exist",
    "Springs",
    "Sprinklers",
    "Squids",
    "Stab the Pope",
    "Statistics",
    "Steam",
    "Steampunk",
    "Stick Figure Death Theatre",
    "Sticky",
    "Stone Age",
    "Story",
    "Strange controls",
    "Stretch",
    "String Theory",
    "Subjective Opinion",
    "Submarines",
    "Suck",
    "Super heroes",
    "Superheroes Performing Mundane Tasks",
    "Surfing",
    "Surrealism",
    "Survival",
    "Swine Flu",
    "Switchboard operator",
    "Sympathetic Antagonist",
    "Synchronization",
    "Synesthesia",
    "Taking Advantage of Weaknesses",
    "Taxes",
    "Team",
    "Team tactics",
    "Teamkilling",
    "Tears",
    "Tech Trees",
    "Telegraphy",
    "Telephone",
    "Teleportation",
    "Television",
    "Temperature",
    "Ten seconds",
    "Tentacles",
    "Tests of strength",
    "Text Mode (80x25x16, etc)",
    "Text-heavy",
    "That was easy, a little too easy",
    "That\\'s impossible!",
    "The [fill in blank]est Hero Ever!",
    "The 80\\'s",
    "The Cows are Everywhere",
    "The Cycle of Life",
    "The est Hero Ever!",
    "The Five Elements (Fire, Earth, Air, Water, Aether)",
    "The Fleet",
    "The game cheats to try to win",
    "The Goal is to Lose",
    "The Hive Mind",
    "The one that got away",
    "The Sea",
    "The Speed of Light",
    "The Tower",
    "The Unknown",
    "Theatrics",
    "There is no spoon",
    "They attack from the shadows",
    "This is not a game",
    "Tiger Woods",
    "Tilt",
    "Time",
    "Time Paradox",
    "Time travel",
    "Time traveling",
    "Timewarp",
    "Tiny",
    "To be played in a public place",
    "Toast",
    "Top hats",
    "Tornadoes",
    "Towlr",
    "Town",
    "Toxic Waste",
    "Toys",
    "Track",
    "Tracking",
    "Trading",
    "Tragedy",
    "Train",
    "Trains",
    "Trampolines",
    "Translucency",
    "Transport",
    "Trash",
    "Travel",
    "Treasure Hunt",
    "Tree falls in the woods",
    "Trees",
    "Tripping",
    "Trophies or awards",
    "Trust",
    "Turbo Hyper Ultra Mega Laser Ninjas 3000",
    "Turn Based Eating",
    "Turn-based strategy",
    "Twilight",
    "Twilight fandom",
    "Two versions of the same thing",
    "Tycoon",
    "UFO",
    "Ugly people in a bar",
    "Unbreakable",
    "Under (beneath, below)",
    "Under the City",
    "Underwater",
    "Unethical business practices",
    "Unfortunate coincidences",
    "Uninteresting occupations",
    "Unique Entities",
    "Universal",
    "Universe",
    "Unlikely Video Game Genre Mixes",
    "Unnameable",
    "Unpretentious Art Game",
    "Unwanted Powers",
    "Unwinnable War",
    "Upside down",
    "Use the whole keyboard",
    "Used cars (buying or selling)",
    "User designed entities(Machines/Gadgets/Organisms)",
    "Vampires, vampiric",
    "Vanishing",
    "Variable-ratio operant conditioning",
    "Vector Field Flows",
    "Vector Flow Fields",
    "Velcro",
    "Velociraptors",
    "Velocity",
    "Velvet Elvis",
    "Versus",
    "Very Short Games",
    "Vi (dual-mode game-play a la vi text editing: e.g. edit & command)",
    "Vicarious interaction through another player",
    "Vicious Squirrels",
    "Video / Webcam",
    "Vikings",
    "Vintage audio playback devices",
    "Violence has consequences",
    "Violent games without the violence",
    "Voices",
    "Volcanoes",
    "Vote fishing",
    "Walkthrough Required",
    "Walrus for breakfast",
    "War",
    "Warped",
    "Washing machines",
    "Waste/garbage",
    "Water",
    "Water Pressure",
    "Wave mechanics of some sort",
    "Weather",
    "Weaving",
    "Werewolves",
    "What I did last weekend: the game!",
    "When animals attack",
    "When the empire takes over, this game will be used as evidence to ensure my immediate execution.",
    "Whodunnit",
    "Wikipedia (the site somehow plays into the game\\'s design)",
    "Wikipedia entry starting with \\'L\\'",
    "Wild animals",
    "Wild West",
    "Win Conditions",
    "Winamp",
    "Wind",
    "Winds",
    "Winnable War",
    "Winter",
    "Wishing wells / wishing on a star",
    "Words",
    "World Cup",
    "World end",
    "World\\'s worst superhero",
    "Wormholes",
    "Worms",
    "WORMS AND ZOMBIES",
    "Wrestling",
    "Xenomorphs",
    "Xenophobia",
    "Xmas spirit",
    "X-Ray Vision",
    "Xylophone",
    "Xyzzy",
    "Yellowstone National Park",
    "Yeti",
    "Ying and Yang",
    "Yodeling",
    "Yoga",
    "Yogurt",
    "You are a cat",
    "You are an unstoppable death machine",
    "You are your own worst enemy",
    "You don\\'t play the main character",
    "You have to cheat to win this game",
    "Your Mother",
    "Yo-yo",
    "Zapping",
    "Zebras",
    "Zero",
    "Zero interaction",
    "Zero Repetition",
    "Zodiac signs",
    "Zombies",
    "Zoo",
    "Zoophobia",
    "ZZZ",];

    var table = 'themes';
    var fieldName = 'theme'
    var startString = `INSERT INTO \`${table}\` (\`${fieldName}\`) VALUES `;

    for (let index = 0; index < textList.length; index++) {
        startString += `(\'${textList[index]}\')`;
        if(index < textList.length - 1)
        {
           startString += ',  \n';
        } else
        {
            startString += ';';
            fs.writeFile('output/sql.txt', startString,  function (err) {
                if (err) return console.log(err);
                console.log('done');
              });
        }
    }